baseURL = 'https://leavex.eu'
languageCode = 'en-us'
title = 'Leave X - Protect Democracy'

[module]
    [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[params]
    homepage.layout = "page"

